[package]
name = "rs-smctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version="0.9.15", features=["std", "driver"], default-features = false }

[patch.crates-io]
cudarc = { git = "https://github.com/atomicapple0/cudarc.git" }
