[package]
name = "rs-smctrl"
version = "0.1.0"
links = "rs-smctrl"
build = "build.rs"
edition = "2021"

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
