/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    pub fn libsmctrl_set_global_mask(mask: u64);
}
extern "C" {
    pub fn libsmctrl_set_stream_mask(stream: *mut ::std::os::raw::c_void, mask: u64);
}
extern "C" {
    pub fn libsmctrl_set_next_mask(mask: u64);
}
extern "C" {
    pub fn libsmctrl_get_gpc_info(
        num_enabled_gpcs: *mut u32,
        tpcs_for_gpc: *mut *mut u64,
        dev: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn libsmctrl_get_tpc_info(
        num_tpcs: *mut u32,
        dev: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn libsmctrl_get_tpc_info_cuda(
        num_tpcs: *mut u32,
        cuda_dev: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
